// Code generated by gostaticstructdiff version 0.1.4. DO NOT EDIT.

package models

import (
	"github.com/andreykyz/gostaticstructdiff/examples/models/nested"
	"reflect"
)

// MetadataDiff represents the diff of a Metadata struct.
type MetadataDiff struct {
	Label *struct {
		Value string
	}
	Values *struct {
		Add map[string]string
		Del map[string]struct{}
	}
	Score *struct {
		Value *float64
	}
	Extra *struct {
		Value struct { Note string `structtomap:"note"`; Cost float64 `structtomap:"cost"` }
	}
}




// MetadataPatch computes the diff between original and new Metadata.
func MetadataPatch(original, new Metadata) MetadataDiff {
	var diff MetadataDiff
	if original.Label != new.Label {
		diff.Label = &struct { Value string }{}
		diff.Label.Value = new.Label
	}
	// Map diff: compute added and deleted keys
	diff.Values = &struct {
		Add map[string]string
		Del map[string]struct{}
	}{}
	diff.Values.Add = make(map[string]string)
	diff.Values.Del = make(map[string]struct{})
	// Added or modified keys
	for k, v := range new.Values {
		oldV, ok := original.Values[k]
		if !ok || !reflect.DeepEqual(oldV, v) {
			diff.Values.Add[k] = v
		}
	}
	// Deleted keys
	for k := range original.Values {
		if _, ok := new.Values[k]; !ok {
			diff.Values.Del[k] = struct{}{}
		}
	}
	if len(diff.Values.Add) == 0 && len(diff.Values.Del) == 0 {
        diff.Values = nil
    }
	if (original.Score == nil && new.Score != nil) || (original.Score != nil && new.Score == nil) || (original.Score != nil && new.Score != nil && *original.Score != *new.Score) {
		diff.Score = &struct { Value *float64 }{}
		diff.Score.Value = new.Score
	}
	if original.Extra != new.Extra {
		diff.Extra = &struct { Value struct { Note string `structtomap:"note"`; Cost float64 `structtomap:"cost"` } }{}
		diff.Extra.Value = new.Extra
	}
	return diff
}

// ApplyMetadataDiff applies a diff to an original Metadata.
func ApplyMetadataDiff(original Metadata, diff MetadataDiff) Metadata {
	result := original
	if diff.Label != nil{
		result.Label = diff.Label.Value
	}
	if diff.Values != nil{
		// Apply map diff
		if result.Values == nil {
			result.Values = make(map[string]string)
		}
		for k, v := range diff.Values.Add {
			result.Values[k] = v
		}
		for k := range diff.Values.Del {
			delete(result.Values, k)
		}
	}
	if diff.Score != nil{
		result.Score = diff.Score.Value
	}
	if diff.Extra != nil{
		result.Extra = diff.Extra.Value
	}
	return result
}

// MetaMetaDiff represents the diff of a MetaMeta map.
type MetaMetaDiff struct {
	Add    map[nested.ID]Metadata
	Modify map[nested.ID]MetadataDiff
	Del    map[nested.ID]struct{}
}

// MetaMetaPatch computes the diff between original and new MetaMeta.
func MetaMetaPatch(original, new MetaMeta) MetaMetaDiff {
	var diff MetaMetaDiff
	diff.Add = make(map[nested.ID]Metadata)
	diff.Modify = make(map[nested.ID]MetadataDiff)
	diff.Del = make(map[nested.ID]struct{})
	// Added or modified keys
	for k, v := range new {
		oldV, ok := original[k]
		if !ok {
			// added key
			diff.Add[k] = v
		} else if !reflect.DeepEqual(oldV, v) {
			// modified key, compute diff
			nestedDiff := MetadataPatch(oldV, v)
			diff.Modify[k] = nestedDiff
		}
	}
	// Deleted keys
	for k := range original {
		if _, ok := new[k]; !ok {
			diff.Del[k] = struct{}{}
		}
	}
	if len(diff.Add) == 0 && len(diff.Modify) == 0 && len(diff.Del) == 0 {
		diff = MetaMetaDiff{}
	}
	return diff
}

// ApplyMetaMetaDiff applies a diff to an original MetaMeta.
func ApplyMetaMetaDiff(original MetaMeta, diff MetaMetaDiff) MetaMeta {
	if original == nil {
		original = make(MetaMeta)
	}
	for k, v := range diff.Add {
		original[k] = v
	}
	for k, v := range diff.Modify {
		existing, ok := original[k]
		if !ok {
			existing = Metadata{}
		}
		original[k] = ApplyMetadataDiff(existing, v)
	}
	for k := range diff.Del {
		delete(original, k)
	}
	return original
}

