// Code generated by gostaticstructdiff version 0.1.3. DO NOT EDIT.

package models

// UserDiff represents the diff of a User struct.
type UserDiff struct {
	ID *struct {
		Value int
	}
	Username *struct {
		Value string
	}
	Email *struct {
		Value string
	}
	Active *struct {
		Value bool
	}
}



// UserPatch computes the diff between original and new User.
func UserPatch(original, new User) UserDiff {
	var diff UserDiff
	if original.ID != new.ID {
		diff.ID = &struct { Value int }{}
		diff.ID.Value = new.ID
	}
	if original.Username != new.Username {
		diff.Username = &struct { Value string }{}
		diff.Username.Value = new.Username
	}
	if original.Email != new.Email {
		diff.Email = &struct { Value string }{}
		diff.Email.Value = new.Email
	}
	if original.Active != new.Active {
		diff.Active = &struct { Value bool }{}
		diff.Active.Value = new.Active
	}
	return diff
}

// ApplyUserDiff applies a diff to an original User.
func ApplyUserDiff(original User, diff UserDiff) User {
	result := original
	if diff.ID != nil{
		result.ID = diff.ID.Value
	}
	if diff.Username != nil{
		result.Username = diff.Username.Value
	}
	if diff.Email != nil{
		result.Email = diff.Email.Value
	}
	if diff.Active != nil{
		result.Active = diff.Active.Value
	}
	return result
}

