// Code generated by gostaticstructdiff version 0.1.3. DO NOT EDIT.

package nested

import (
	"reflect"
)

// MetaStringDiff represents the diff of a MetaString map.
type MetaStringDiff struct {
	Add map[string]string
	Del map[string]struct{}
}

// MetaStringPatch computes the diff between original and new MetaString.
func MetaStringPatch(original, new MetaString) MetaStringDiff {
	var diff MetaStringDiff
	diff.Add = make(map[string]string)
	diff.Del = make(map[string]struct{})
	// Added or modified keys
	for k, v := range new {
		oldV, ok := original[k]
		if !ok || !reflect.DeepEqual(oldV, v) {
			diff.Add[k] = v
		}
	}
	// Deleted keys
	for k := range original {
		if _, ok := new[k]; !ok {
			diff.Del[k] = struct{}{}
		}
	}
	if len(diff.Add) == 0 && len(diff.Del) == 0 {
		diff = MetaStringDiff{}
	}
	return diff
}

// ApplyMetaStringDiff applies a diff to an original MetaString.
func ApplyMetaStringDiff(original MetaString, diff MetaStringDiff) MetaString {
	if original == nil {
		original = make(MetaString)
	}
	for k, v := range diff.Add {
		original[k] = v
	}
	for k := range diff.Del {
		delete(original, k)
	}
	return original
}

