package generator

import (
	"bytes"
	"embed"
	"fmt"
	"go/ast"
	"strings"
	"text/template"

	"github.com/andreykyz/gostaticstructdiff/parser"
	"github.com/andreykyz/gostaticstructdiff/types"
)

//go:embed templates/*
var templateFS embed.FS

// FieldTemplateData holds data for a field in the template.
type FieldTemplateData struct {
	Name                   string
	Type                   string
	Category               string
	KeyType                string
	ValueType              string
	ValueIsStruct          bool
	ValueDiffType          string
	ValueTypePackage       string // package of ValueType (empty if same package)
	ValueTypeName          string // name of ValueType without package
	ValueDiffFunc          string // qualified function name to apply diff (e.g., "models.ApplyMetadataDiff")
	ElementIsStruct        bool
	ElementDiffType        string
	ElementTypePackage     string // package of ElementType (empty if same package)
	ElementTypeName        string // name of ElementType without package
	ElementDiffFunc        string // qualified function name to apply diff for slice elements
	StructTypePackage      string // package of struct type (empty if same package)
	StructTypeName         string // name of struct type without package
	StructDiffFunc         string // qualified function name to apply diff for struct fields (e.g., "models.ApplyUserDiff")
	PointerElementIsStruct bool
	PointerElementType     string // underlying struct type for pointer-to-struct (e.g., "models.User")
	PointerDiffType        string // diff type for pointer-to-struct (e.g., "models.UserDiff")
	PointerDiffFunc        string // apply diff function for pointer-to-struct (e.g., "models.ApplyUserDiff")
	IsAnonymous            bool
}

// StructTemplateData holds data for a struct in the template.
type StructTemplateData struct {
	Name   string
	Fields []FieldTemplateData
}

// MapAliasTemplateData holds data for a map alias type in the template.
type MapAliasTemplateData struct {
	Name             string
	KeyType          string
	ValueType        string
	ValueIsStruct    bool
	ValueDiffType    string
	ValueTypePackage string
	ValueTypeName    string
	ValueDiffFunc    string
}

// Generate generates diff code for the given structs and writes to output.
func Generate(structs []parser.StructInfo, packageName string, imports []string, version string, typeDefs map[string]ast.Expr, verbose bool) (string, error) {
	if verbose {
		fmt.Printf("Generating code for %d struct(s) in package %s\n", len(structs), packageName)
	}

	// Load templates
	tmpl, err := loadTemplates()
	if err != nil {
		return "", fmt.Errorf("failed to load templates: %w", err)
	}

	// Build a set of known struct names (from the same package)
	knownStructs := make(map[string]bool)
	for _, s := range structs {
		knownStructs[s.Name] = true
	}

	// Determine if we need reflect import
	needsReflect := false
	for _, s := range structs {
		for _, f := range s.Fields {
			typeInfo := types.Classify(f.TypeExpr, knownStructs, typeDefs)
			if typeInfo.Category == types.CategorySlice || typeInfo.Category == types.CategoryMap || typeInfo.Category == types.CategoryMapAlias || typeInfo.Category == types.CategoryUnknown {
				needsReflect = true
				break
			}
		}
		if needsReflect {
			break
		}
	}

	// Add reflect import if needed and not already present
	if needsReflect {
		hasReflect := false
		for _, imp := range imports {
			if imp == "reflect" {
				hasReflect = true
				break
			}
		}
		if !hasReflect {
			imports = append(imports, "reflect")
		}
		if verbose {
			fmt.Printf("  Added reflect import (needed for slice/map/unknown types)\n")
		}
	}

	// Prepare data for each struct
	var output bytes.Buffer

	// Write package declaration
	output.WriteString(fmt.Sprintf("// Code generated by gostaticstructdiff version %s. DO NOT EDIT.\n\n", version))
	output.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// Write imports if any
	if len(imports) > 0 {
		output.WriteString("import (\n")
		for _, imp := range imports {
			output.WriteString(fmt.Sprintf("\t\"%s\"\n", imp))
		}
		output.WriteString(")\n\n")
	}

	// Generate each struct diff
	for _, s := range structs {
		if verbose {
			fmt.Printf("  Generating diff for struct %s (%d fields)\n", s.Name, len(s.Fields))
		}
		data := convertToTemplateData(s, knownStructs, typeDefs)
		err = tmpl.ExecuteTemplate(&output, "struct_diff.go.tmpl", data)
		if err != nil {
			return "", fmt.Errorf("failed to execute struct template for %s: %w", s.Name, err)
		}
		output.WriteString("\n\n")

		// Generate patch functions
		err = tmpl.ExecuteTemplate(&output, "patch_func.go.tmpl", data)
		if err != nil {
			return "", fmt.Errorf("failed to execute patch template for %s: %w", s.Name, err)
		}
		output.WriteString("\n\n")
	}

	// Collect and generate diff types for referenced map aliases
	mapAliases := collectReferencedMapAliases(structs, typeDefs, knownStructs)
	generatedMapAliases := make(map[string]bool)
	for _, ma := range mapAliases {
		if generatedMapAliases[ma.Name] {
			continue
		}
		generatedMapAliases[ma.Name] = true
		if verbose {
			fmt.Printf("  Generating diff for map alias %s\n", ma.Name)
		}
		err = tmpl.ExecuteTemplate(&output, "map_alias_diff.go.tmpl", ma)
		if err != nil {
			return "", fmt.Errorf("failed to execute map alias template for %s: %w", ma.Name, err)
		}
		output.WriteString("\n\n")

		err = tmpl.ExecuteTemplate(&output, "map_alias_patch.go.tmpl", ma)
		if err != nil {
			return "", fmt.Errorf("failed to execute map alias patch template for %s: %w", ma.Name, err)
		}
		output.WriteString("\n\n")
	}

	if verbose {
		fmt.Printf("Generation completed for %d struct(s) and %d map alias(es)\n", len(structs), len(mapAliases))
	}

	return output.String(), nil
}

// splitType splits a type string like "models.Metadata" into package and name.
// If there's no dot, package is empty.
func splitType(typeStr string) (pkg, name string) {
	if idx := strings.LastIndex(typeStr, "."); idx != -1 {
		return typeStr[:idx], typeStr[idx+1:]
	}
	return "", typeStr
}

// convertToTemplateData converts a parser.StructInfo to StructTemplateData.
// knownStructs is a set of type names that are known to be structs.
// typeDefs is a map of type names to their underlying AST expressions.
func convertToTemplateData(s parser.StructInfo, knownStructs map[string]bool, typeDefs map[string]ast.Expr) StructTemplateData {
	data := StructTemplateData{
		Name:   s.Name,
		Fields: make([]FieldTemplateData, 0, len(s.Fields)),
	}

	for _, f := range s.Fields {
		typeInfo := types.Classify(f.TypeExpr, knownStructs, typeDefs)
		category := typeInfo.Category.String()
		isAnonymous := false

		// Detect anonymous structs (type string starts with "struct {")
		if typeInfo.Category == types.CategoryStruct && strings.HasPrefix(typeInfo.TypeString, "struct {") {
			// Treat anonymous structs as basic (comparable) for simplicity
			category = "basic"
			isAnonymous = true
		}

		// Detect pointer to struct
		if typeInfo.Category == types.CategoryPointer && typeInfo.Element != nil && typeInfo.Element.Category == types.CategoryStruct {
			category = "pointerStruct"
		}

		// Treat unknown types as slice (use reflect.DeepEqual)
		if typeInfo.Category == types.CategoryUnknown {
			category = "slice"
		}

		fieldData := FieldTemplateData{
			Name:        f.Name,
			Type:        f.Type,
			Category:    category,
			IsAnonymous: isAnonymous,
		}

		// For map types, extract key and value types
		if (typeInfo.Category == types.CategoryMap || typeInfo.Category == types.CategoryMapAlias) && typeInfo.Key != nil && typeInfo.Value != nil {
			fieldData.KeyType = typeInfo.Key.TypeString
			fieldData.ValueType = typeInfo.Value.TypeString
			if typeInfo.Value.Category == types.CategoryStruct {
				fieldData.ValueIsStruct = true
				fieldData.ValueDiffType = typeInfo.Value.TypeString + "Diff"
				// Compute package and name for apply function
				pkg, name := splitType(typeInfo.Value.TypeString)
				fieldData.ValueTypePackage = pkg
				fieldData.ValueTypeName = name
				if pkg != "" {
					fieldData.ValueDiffFunc = pkg + ".Apply" + name + "Diff"
				} else {
					fieldData.ValueDiffFunc = "Apply" + name + "Diff"
				}
			}
		}

		// For slice types, extract element type
		if typeInfo.Category == types.CategorySlice && typeInfo.Element != nil {
			if typeInfo.Element.Category == types.CategoryStruct {
				fieldData.ElementIsStruct = true
				fieldData.ElementDiffType = typeInfo.Element.TypeString + "Diff"
				// Compute package and name for apply function
				pkg, name := splitType(typeInfo.Element.TypeString)
				fieldData.ElementTypePackage = pkg
				fieldData.ElementTypeName = name
				if pkg != "" {
					fieldData.ElementDiffFunc = pkg + ".Apply" + name + "Diff"
				} else {
					fieldData.ElementDiffFunc = "Apply" + name + "Diff"
				}
			}
		}

		// For pointer-to-struct types, extract element type
		if typeInfo.Category == types.CategoryPointer && typeInfo.Element != nil && typeInfo.Element.Category == types.CategoryStruct {
			fieldData.PointerElementIsStruct = true
			fieldData.PointerElementType = typeInfo.Element.TypeString
			fieldData.PointerDiffType = typeInfo.Element.TypeString + "Diff"
			// Compute package and name for apply function
			pkg, name := splitType(typeInfo.Element.TypeString)
			if pkg != "" {
				fieldData.PointerDiffFunc = pkg + ".Apply" + name + "Diff"
			} else {
				fieldData.PointerDiffFunc = "Apply" + name + "Diff"
			}
		}

		// For struct types and map alias types, compute diff function
		if (typeInfo.Category == types.CategoryStruct || typeInfo.Category == types.CategoryMapAlias) && !isAnonymous {
			pkg, name := splitType(typeInfo.TypeString)
			fieldData.StructTypePackage = pkg
			fieldData.StructTypeName = name
			if pkg != "" {
				fieldData.StructDiffFunc = pkg + ".Apply" + name + "Diff"
			} else {
				fieldData.StructDiffFunc = "Apply" + name + "Diff"
			}
		}

		data.Fields = append(data.Fields, fieldData)
	}

	return data
}

// collectReferencedMapAliases scans struct fields and typeDefs for map alias types
// and returns template data for generating their diff types.
func collectReferencedMapAliases(structs []parser.StructInfo, typeDefs map[string]ast.Expr, knownStructs map[string]bool) []MapAliasTemplateData {
	seen := make(map[string]bool)
	var result []MapAliasTemplateData

	// First, scan struct fields for map alias references
	for _, s := range structs {
		for _, f := range s.Fields {
			typeInfo := types.Classify(f.TypeExpr, knownStructs, typeDefs)
			if typeInfo.Category != types.CategoryMapAlias {
				continue
			}
			if seen[typeInfo.TypeString] {
				continue
			}
			seen[typeInfo.TypeString] = true

			ma := MapAliasTemplateData{
				Name:      typeInfo.TypeString,
				KeyType:   typeInfo.Key.TypeString,
				ValueType: typeInfo.Value.TypeString,
			}

			if typeInfo.Value.Category == types.CategoryStruct {
				ma.ValueIsStruct = true
				ma.ValueDiffType = typeInfo.Value.TypeString + "Diff"
				pkg, name := splitType(typeInfo.Value.TypeString)
				ma.ValueTypePackage = pkg
				ma.ValueTypeName = name
				if pkg != "" {
					ma.ValueDiffFunc = pkg + ".Apply" + name + "Diff"
				} else {
					ma.ValueDiffFunc = "Apply" + name + "Diff"
				}
			}

			result = append(result, ma)
		}
	}

	// Also scan typeDefs directly for map alias types that aren't referenced by fields
	// but are defined in the same package (e.g., type MetaMeta map[nested.ID]Metadata)
	for name, underlying := range typeDefs {
		if seen[name] {
			continue
		}
		// Check if the underlying type is a map
		mapType, ok := underlying.(*ast.MapType)
		if !ok {
			continue
		}
		// Classify the key and value types
		keyInfo := types.Classify(mapType.Key, knownStructs, typeDefs)
		valueInfo := types.Classify(mapType.Value, knownStructs, typeDefs)

		ma := MapAliasTemplateData{
			Name:      name,
			KeyType:   keyInfo.TypeString,
			ValueType: valueInfo.TypeString,
		}

		if valueInfo.Category == types.CategoryStruct {
			ma.ValueIsStruct = true
			ma.ValueDiffType = valueInfo.TypeString + "Diff"
			pkg, name := splitType(valueInfo.TypeString)
			ma.ValueTypePackage = pkg
			ma.ValueTypeName = name
			if pkg != "" {
				ma.ValueDiffFunc = pkg + ".Apply" + name + "Diff"
			} else {
				ma.ValueDiffFunc = "Apply" + name + "Diff"
			}
		}

		seen[name] = true
		result = append(result, ma)
	}

	return result
}

// loadTemplates loads all template files from the embedded filesystem.
func loadTemplates() (*template.Template, error) {
	// Parse all templates from the embedded filesystem.
	// The template names are the base names of the files.
	tmpl, err := template.ParseFS(templateFS, "templates/*.tmpl")
	if err != nil {
		return nil, fmt.Errorf("failed to parse templates: %w", err)
	}
	return tmpl, nil
}
