// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package gostaticstructdiff

import (
	"errors"
	"fmt"
)

const (
	// NestedTypeMap is a NestedType of type Map.
	NestedTypeMap NestedType = iota
	// NestedTypeSlice is a NestedType of type Slice.
	NestedTypeSlice
)

var ErrInvalidNestedType = errors.New("not a valid NestedType")

const _NestedTypeName = "mapslice"

var _NestedTypeMap = map[NestedType]string{
	NestedTypeMap:   _NestedTypeName[0:3],
	NestedTypeSlice: _NestedTypeName[3:8],
}

// String implements the Stringer interface.
func (x NestedType) String() string {
	if str, ok := _NestedTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("NestedType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x NestedType) IsValid() bool {
	_, ok := _NestedTypeMap[x]
	return ok
}

var _NestedTypeValue = map[string]NestedType{
	_NestedTypeName[0:3]: NestedTypeMap,
	_NestedTypeName[3:8]: NestedTypeSlice,
}

// ParseNestedType attempts to convert a string to a NestedType.
func ParseNestedType(name string) (NestedType, error) {
	if x, ok := _NestedTypeValue[name]; ok {
		return x, nil
	}
	return NestedType(0), fmt.Errorf("%s is %w", name, ErrInvalidNestedType)
}
