// Code generated by gostaticstructdiff version 0.1.3. DO NOT EDIT.

package examples

import (
	"github.com/andreykyz/gostaticstructdiff/examples/models"
	"github.com/andreykyz/gostaticstructdiff/examples/models/nested"
	"reflect"
)

// ComplexStructDiff represents the diff of a ComplexStruct struct.
type ComplexStructDiff struct {
	Name *struct {
		Value string
	}
	GGID *struct {
		Value nested.GGID
	}
	Count *struct {
		Value int
	}
	Active *struct {
		Value bool
	}
	Tags *struct {
		Value []string
	}
	Users *struct {
		Value []models.User
	}
	Metadata *struct {
		Add map[string]models.Metadata
		Modify map[string]models.MetadataDiff
		Del map[string]struct{}
	}
	MetaMeta *struct {
		Value models.MetaMetaDiff
	}
	MetaString *struct {
		Value nested.MetaStringDiff
	}
	Inner *struct {
		Value struct { Title string `structtomap:"title"`; Value int `structtomap:"value"` }
	}
	StaticUser *struct {
		Value models.UserDiff
	}
	Ref *struct {
		NewValue *models.User
		Diff     *models.UserDiff
	}
	Categories *struct {
		Add map[string][]string
		Del map[string]struct{}
	}
}




// ComplexStructPatch computes the diff between original and new ComplexStruct.
func ComplexStructPatch(original, new ComplexStruct) ComplexStructDiff {
	var diff ComplexStructDiff
	if original.Name != new.Name {
		diff.Name = &struct { Value string }{}
		diff.Name.Value = new.Name
	}
	if original.GGID != new.GGID {
		diff.GGID = &struct { Value nested.GGID }{}
		diff.GGID.Value = new.GGID
	}
	if original.Count != new.Count {
		diff.Count = &struct { Value int }{}
		diff.Count.Value = new.Count
	}
	if original.Active != new.Active {
		diff.Active = &struct { Value bool }{}
		diff.Active.Value = new.Active
	}
	// Slice comparison using reflect.DeepEqual
	if !reflect.DeepEqual(original.Tags, new.Tags) {
		diff.Tags = &struct { Value []string }{}
		diff.Tags.Value = new.Tags
	}
	// Slice comparison using reflect.DeepEqual
	if !reflect.DeepEqual(original.Users, new.Users) {
		diff.Users = &struct { Value []models.User }{}
		diff.Users.Value = new.Users
	}
	// Map diff with nested struct values
	diff.Metadata = &struct {
		Add map[string]models.Metadata
		Modify map[string]models.MetadataDiff
		Del map[string]struct{}
	}{}
	diff.Metadata.Add = make(map[string]models.Metadata)
	diff.Metadata.Modify = make(map[string]models.MetadataDiff)
	diff.Metadata.Del = make(map[string]struct{})
	// Added or modified keys
	for k, v := range new.Metadata {
		oldV, ok := original.Metadata[k]
		if !ok {
			// added key
			diff.Metadata.Add[k] = v
		} else if !reflect.DeepEqual(oldV, v) {
			// modified key, compute diff
			nestedDiff := models.MetadataPatch(oldV, v)
			diff.Metadata.Modify[k] = nestedDiff
		}
	}
	// Deleted keys
	for k := range original.Metadata {
		if _, ok := new.Metadata[k]; !ok {
			diff.Metadata.Del[k] = struct{}{}
		}
	}
	if len(diff.Metadata.Add) == 0 && len(diff.Metadata.Modify) == 0 && len(diff.Metadata.Del) == 0 {
        diff.Metadata = nil
    }
	// Nested struct diff
	MetaMetaNestedDiff := models.MetaMetaPatch(original.MetaMeta, new.MetaMeta)
	diff.MetaMeta = &struct { Value models.MetaMetaDiff }{}
	diff.MetaMeta.Value = MetaMetaNestedDiff
	// Nested struct diff
	MetaStringNestedDiff := nested.MetaStringPatch(original.MetaString, new.MetaString)
	diff.MetaString = &struct { Value nested.MetaStringDiff }{}
	diff.MetaString.Value = MetaStringNestedDiff
	if original.Inner != new.Inner {
		diff.Inner = &struct { Value struct { Title string `structtomap:"title"`; Value int `structtomap:"value"` } }{}
		diff.Inner.Value = new.Inner
	}
	// Nested struct diff
	StaticUserNestedDiff := models.UserPatch(original.StaticUser, new.StaticUser)
	diff.StaticUser = &struct { Value models.UserDiff }{}
	diff.StaticUser.Value = StaticUserNestedDiff
	// Pointer-to-struct diff
	if original.Ref == nil && new.Ref == nil {
		// both nil, no change
	} else if original.Ref == nil && new.Ref != nil {
		// added pointer
		diff.Ref = &struct {
			NewValue *models.User
			Diff     *models.UserDiff
		}{}
		diff.Ref.NewValue = new.Ref
	} else if original.Ref != nil && new.Ref == nil {
		// removed pointer
		diff.Ref = &struct {
			NewValue *models.User
			Diff     *models.UserDiff
		}{}
		diff.Ref.NewValue = nil
	} else {
		// both non-nil, compare content
		if !reflect.DeepEqual(*original.Ref, *new.Ref) {
			nestedDiff := models.UserPatch(*original.Ref, *new.Ref)
			diff.Ref = &struct {
				NewValue *models.User
				Diff     *models.UserDiff
			}{}
			diff.Ref.Diff = &nestedDiff
		}
	}
	// Map diff: compute added and deleted keys
	diff.Categories = &struct {
		Add map[string][]string
		Del map[string]struct{}
	}{}
	diff.Categories.Add = make(map[string][]string)
	diff.Categories.Del = make(map[string]struct{})
	// Added or modified keys
	for k, v := range new.Categories {
		oldV, ok := original.Categories[k]
		if !ok || !reflect.DeepEqual(oldV, v) {
			diff.Categories.Add[k] = v
		}
	}
	// Deleted keys
	for k := range original.Categories {
		if _, ok := new.Categories[k]; !ok {
			diff.Categories.Del[k] = struct{}{}
		}
	}
	if len(diff.Categories.Add) == 0 && len(diff.Categories.Del) == 0 {
        diff.Categories = nil
    }
	return diff
}

// ApplyComplexStructDiff applies a diff to an original ComplexStruct.
func ApplyComplexStructDiff(original ComplexStruct, diff ComplexStructDiff) ComplexStruct {
	result := original
	if diff.Name != nil{
		result.Name = diff.Name.Value
	}
	if diff.GGID != nil{
		result.GGID = diff.GGID.Value
	}
	if diff.Count != nil{
		result.Count = diff.Count.Value
	}
	if diff.Active != nil{
		result.Active = diff.Active.Value
	}
	if diff.Tags != nil{
		result.Tags = diff.Tags.Value
	}
	if diff.Users != nil{
		result.Users = diff.Users.Value
	}
	if diff.Metadata != nil{
		// Apply map diff
		if result.Metadata == nil {
			result.Metadata = make(map[string]models.Metadata)
		}
		for k, v := range diff.Metadata.Add {
			// v is a models.Metadata (whole value), assign directly
			result.Metadata[k] = v
		}
		for k, v := range diff.Metadata.Modify {
			// v is a models.MetadataDiff, apply it to the existing value (or zero)
			existing, ok := result.Metadata[k]
			if !ok {
				existing = models.Metadata{}
			}
			result.Metadata[k] = models.ApplyMetadataDiff(existing, v)
		}
		for k := range diff.Metadata.Del {
			delete(result.Metadata, k)
		}
	}
	if diff.MetaMeta != nil{
		result.MetaMeta = models.ApplyMetaMetaDiff(original.MetaMeta, diff.MetaMeta.Value)
	}
	if diff.MetaString != nil{
		result.MetaString = nested.ApplyMetaStringDiff(original.MetaString, diff.MetaString.Value)
	}
	if diff.Inner != nil{
		result.Inner = diff.Inner.Value
	}
	if diff.StaticUser != nil{
		result.StaticUser = models.ApplyUserDiff(original.StaticUser, diff.StaticUser.Value)
	}
	if diff.Ref != nil{
		if diff.Ref.NewValue != nil {
			result.Ref = diff.Ref.NewValue
		} else if diff.Ref.Diff != nil {
			// Apply diff to existing pointer (must be non-nil)
			if original.Ref == nil {
				// If original is nil, create zero value
				zero := models.User{}
				result.Ref = &zero
			} else {
				result.Ref = original.Ref
			}
			*result.Ref = models.ApplyUserDiff(*original.Ref, *diff.Ref.Diff)
		}
	}
	if diff.Categories != nil{
		// Apply map diff
		if result.Categories == nil {
			result.Categories = make(map[string][]string)
		}
		for k, v := range diff.Categories.Add {
			result.Categories[k] = v
		}
		for k := range diff.Categories.Del {
			delete(result.Categories, k)
		}
	}
	return result
}

