// Code generated by gostaticstructdiff version 0.1.3. DO NOT EDIT.

package examples

import (
	"github.com/andreykyz/gostaticstructdiff/examples/models"
	"reflect"
)

// ComplexStructDiff represents the diff of a ComplexStruct struct.
type ComplexStructDiff struct {
	Name *struct {
		Value string
	}
	Count *struct {
		Value int
	}
	Active *struct {
		Value bool
	}
	Tags *struct {
		Value []string
	}
	Users *struct {
		Value []models.User
	}
	Metadata *struct {
		Add map[string]models.Metadata
		Modify map[string]models.MetadataDiff
		Del map[string]struct{}
	}
	Inner *struct {
		Value struct { Title string `structtomap:"title"`; Value int `structtomap:"value"` }
	}
	StaticUser *struct {
		Value models.UserDiff
	}
	Ref *struct {
		Value *models.User
	}
	Categories *struct {
		Add map[string][]string
		Del map[string]struct{}
	}
}



// ComplexStructPatch computes the diff between original and new ComplexStruct.
func ComplexStructPatch(original, new ComplexStruct) ComplexStructDiff {
	var diff ComplexStructDiff
	if original.Name != new.Name {
		diff.Name = &struct { Value string }{}
		diff.Name.Value = new.Name
	}
	if original.Count != new.Count {
		diff.Count = &struct { Value int }{}
		diff.Count.Value = new.Count
	}
	if original.Active != new.Active {
		diff.Active = &struct { Value bool }{}
		diff.Active.Value = new.Active
	}
	// Slice comparison using reflect.DeepEqual
	if !reflect.DeepEqual(original.Tags, new.Tags) {
		diff.Tags = &struct { Value []string }{}
		diff.Tags.Value = new.Tags
	}
	// Slice comparison using reflect.DeepEqual
	if !reflect.DeepEqual(original.Users, new.Users) {
		diff.Users = &struct { Value []models.User }{}
		diff.Users.Value = new.Users
	}
	// Map diff with nested struct values
	diff.Metadata = &struct {
		Add map[string]models.Metadata
		Modify map[string]models.MetadataDiff
		Del map[string]struct{}
	}{}
	diff.Metadata.Add = make(map[string]models.Metadata)
	diff.Metadata.Modify = make(map[string]models.MetadataDiff)
	diff.Metadata.Del = make(map[string]struct{})
	// Added or modified keys
	for k, v := range new.Metadata {
		oldV, ok := original.Metadata[k]
		if !ok {
			// added key
			diff.Metadata.Add[k] = v
		} else if !reflect.DeepEqual(oldV, v) {
			// modified key, compute diff
			nestedDiff := models.MetadataPatch(oldV, v)
			diff.Metadata.Modify[k] = nestedDiff
		}
	}
	// Deleted keys
	for k := range original.Metadata {
		if _, ok := new.Metadata[k]; !ok {
			diff.Metadata.Del[k] = struct{}{}
		}
	}
	if original.Inner != new.Inner {
		diff.Inner = &struct { Value struct { Title string `structtomap:"title"`; Value int `structtomap:"value"` } }{}
		diff.Inner.Value = new.Inner
	}
	// Nested struct diff
	nestedDiff := models.UserPatch(original.StaticUser, new.StaticUser)
	diff.StaticUser = &struct { Value models.UserDiff }{}
	diff.StaticUser.Value = nestedDiff
	if (original.Ref == nil && new.Ref != nil) || (original.Ref != nil && new.Ref == nil) || (original.Ref != nil && new.Ref != nil && *original.Ref != *new.Ref) {
		diff.Ref = &struct { Value *models.User }{}
		diff.Ref.Value = new.Ref
	}
	// Map diff: compute added and deleted keys
	diff.Categories = &struct {
		Add map[string][]string
		Del map[string]struct{}
	}{}
	diff.Categories.Add = make(map[string][]string)
	diff.Categories.Del = make(map[string]struct{})
	// Added or modified keys
	for k, v := range new.Categories {
		oldV, ok := original.Categories[k]
		if !ok || !reflect.DeepEqual(oldV, v) {
			diff.Categories.Add[k] = v
		}
	}
	// Deleted keys
	for k := range original.Categories {
		if _, ok := new.Categories[k]; !ok {
			diff.Categories.Del[k] = struct{}{}
		}
	}
	return diff
}

// ApplyComplexStructDiff applies a diff to an original ComplexStruct.
func ApplyComplexStructDiff(original ComplexStruct, diff ComplexStructDiff) ComplexStruct {
	result := original
	if diff.Name != nil{
		result.Name = diff.Name.Value
	}
	if diff.Count != nil{
		result.Count = diff.Count.Value
	}
	if diff.Active != nil{
		result.Active = diff.Active.Value
	}
	if diff.Tags != nil{
		result.Tags = diff.Tags.Value
	}
	if diff.Users != nil{
		result.Users = diff.Users.Value
	}
	if diff.Metadata != nil{
		// Apply map diff
		if result.Metadata == nil {
			result.Metadata = make(map[string]models.Metadata)
		}
		for k, v := range diff.Metadata.Add {
			// v is a models.Metadata (whole value), assign directly
			result.Metadata[k] = v
		}
		for k, v := range diff.Metadata.Modify {
			// v is a models.MetadataDiff, apply it to the existing value (or zero)
			existing, ok := result.Metadata[k]
			if !ok {
				existing = models.Metadata{}
			}
			result.Metadata[k] = models.ApplyMetadataDiff(existing, v)
		}
		for k := range diff.Metadata.Del {
			delete(result.Metadata, k)
		}
	}
	if diff.Inner != nil{
		result.Inner = diff.Inner.Value
	}
	if diff.StaticUser != nil{
		result.StaticUser = models.ApplyUserDiff(original.StaticUser, diff.StaticUser.Value)
	}
	if diff.Ref != nil{
		result.Ref = diff.Ref.Value
	}
	if diff.Categories != nil{
		// Apply map diff
		if result.Categories == nil {
			result.Categories = make(map[string][]string)
		}
		for k, v := range diff.Categories.Add {
			result.Categories[k] = v
		}
		for k := range diff.Categories.Del {
			delete(result.Categories, k)
		}
	}
	return result
}

